APP = spike_source_remote_poisson_rbf
BUILD_DIR = build/
CFLAGS += -DPOISSON -DRBF -mthumb #-interwork
OBJECTS = ../../common/out_spikes.o spike_source_remote_poisson_rbf.o

include ../../Makefile.common
